version: "3.3"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"  # Backend accessible sur localhost:3000
    networks:
      - webnet
    depends_on:
      - db  # Le backend dépend de la base de données
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=mydb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"  # Frontend accessible sur localhost:8080
    depends_on:
      - backend
    networks:
      - webnet

  db:
    build: ./database  # Build à partir de database/Dockerfile
    container_name: tp-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data  # Volume pour persister les données
    networks:
      - webnet
    ports:
      - "5432:5432"  # Optionnel : accès local à la base

networks:
  webnet:  # Réseau bridge personnalisé pour la communication
    

volumes:
  db-data:  # Volume nommé pour la persistance des données

